# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: write-all

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Pull Images
        id: loop
        run: |
          for tag in 23.0.3 22.0.5 22.0.0 21.0.1 21.1.2 18.0.0-legacy
          do
            docker pull quay.io/keycloak/keycloak:$tag
          done
      - name: Tag Images
        id: loop2
        run: |
          for tag in 23.0.3 22.0.5 22.0.0 21.0.1 21.1.2 18.0.0-legacy
          do
            docker tag quay.io/keycloak/keycloak:$tag ghcr.io/rmkanda/keycloak-images/keycloak:$tag
          done
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Images
        id: loop3
        run: |
          for tag in 23.0.3 22.0.5 22.0.0 21.0.1 21.1.2 18.0.0-legacy
          do
            docker push ghcr.io/rmkanda/keycloak-images/keycloak:$tag
          done
